title: Dave Brimley
description: Thoughts on Distributed Systems and In Memory Data Grids (IMDG)

url: http://davebrimley.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
gems: ["jekyll-paginate","jekyll-sitemap"]
paginate: 5
paginate_path: "page:num"

navigation:
 - title: Home
   url: /index.html
 - title: Talks
   url: /talks
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: dbrimley
   twitter: dbrimley
   email: david@craftedbytes.com

google_analytics: "UA-57685522-1"
